[package]
name = "rad_ext_template"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/simhyeon/r4d"
description = "Rad ext macro template macros"
repository = "https://github.com/simhyeon/r4d"

[lib]
proc-macro = true

[features]
binary = []
